# DS-SF-27 | Unit Project 3: Basic Machine Learning Modeling

In this project, you will perform a logistic regression on the admissions data we've been working with in Unit Projects 1 and 2.

In [1]:
import os

import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)
pd.set_option('display.notebook_repr_html', True)

import statsmodels.formula.api as smf

from sklearn import linear_model

In [25]:
df = pd.read_csv(os.path.join('..', '..', 'dataset', 'ucla-admissions.csv'))
df.dropna(inplace = True)

df

admit    gre   gpa  prestige
0        0  380.0  3.61       3.0
1        1  660.0  3.67       3.0
2        1  800.0  4.00       1.0
3        1  640.0  3.19       4.0
4        0  520.0  2.93       4.0
..     ...    ...   ...       ...
395      0  620.0  4.00       2.0
396      0  560.0  3.04       3.0
397      0  460.0  2.63       2.0
398      0  700.0  3.65       2.0
399      0  600.0  3.89       3.0

[397 rows x 4 columns]

## Part A.  Frequency Table

> ### Question 1.  Create a frequency table for `prestige` and whether or not an applicant was admitted.

In [ ]:
# TODO

## Part B.  Variable Transformations

> ### Question 2.  Create a one-hot encoding for `prestige`.

In [ ]:
# TODO

> ### Question 3.  How many of these binary variables do we need for modeling?

Answer:

> ### Question 4.  Why are we doing this?

Answer:

> ### Question 5.  Add all these binary variables in the dataset and remove the now redundant `prestige` feature.

In [26]:
cs = pd.get_dummies(df['prestige'], prefix='prestige')
cs.drop('prestige_1.0', axis=1, inplace=True)
cs

prestige_2.0  prestige_3.0  prestige_4.0
0             0.0           1.0           0.0
1             0.0           1.0           0.0
2             0.0           0.0           0.0
3             0.0           0.0           1.0
4             0.0           0.0           1.0
..            ...           ...           ...
395           1.0           0.0           0.0
396           0.0           1.0           0.0
397           1.0           0.0           0.0
398           1.0           0.0           0.0
399           0.0           1.0           0.0

[397 rows x 3 columns]

In [27]:
# TODO

df.drop('prestige', axis=1, inplace=True)
df

admit    gre   gpa
0        0  380.0  3.61
1        1  660.0  3.67
2        1  800.0  4.00
3        1  640.0  3.19
4        0  520.0  2.93
..     ...    ...   ...
395      0  620.0  4.00
396      0  560.0  3.04
397      0  460.0  2.63
398      0  700.0  3.65
399      0  600.0  3.89

[397 rows x 3 columns]

In [28]:
dfnew = pd.concat((df, cs), axis=1)
dfnew.columns = ['admit', 'gre', 'gpa', 'prestige2', 'prestige3', 'prestige4']
dfnew

admit    gre   gpa  prestige2  prestige3  prestige4
0        0  380.0  3.61        0.0        1.0        0.0
1        1  660.0  3.67        0.0        1.0        0.0
2        1  800.0  4.00        0.0        0.0        0.0
3        1  640.0  3.19        0.0        0.0        1.0
4        0  520.0  2.93        0.0        0.0        1.0
..     ...    ...   ...        ...        ...        ...
395      0  620.0  4.00        1.0        0.0        0.0
396      0  560.0  3.04        0.0        1.0        0.0
397      0  460.0  2.63        1.0        0.0        0.0
398      0  700.0  3.65        1.0        0.0        0.0
399      0  600.0  3.89        0.0        1.0        0.0

[397 rows x 6 columns]

## Part C.  Hand calculating odds ratios

Let's develop our intuition about expected outcomes by hand calculating odds ratios.

> ### Question 6.  Create a frequency table for `prestige = 1` and whether or not an applicant was admitted.

In [ ]:
# TODO

> ### Question 7.  Use the frequency table above to calculate the odds of being admitted to graduate school for applicants that attended the most prestigious undergraduate schools.

In [ ]:
# TODO

> ### Question 8.  Now calculate the odds of admission for undergraduates who did not attend a #1 ranked college.

In [ ]:
# TODO

> ### Question 9.  Finally, what's the odds ratio?

In [ ]:
# TODO

> ### Question 10.  Write this finding in a sentenance.

Answer:

> ### Question 11.  Use the frequency table above to calculate the odds of being admitted to graduate school for applicants that attended the least prestigious undergraduate schools.  Then calculate their odds ratio of being admitted to UCLA.  Finally, write this finding in a sentenance.

In [ ]:
# TODO

Answer:

## Part C. Analysis using `statsmodels`

> ### Question 12.  Fit a logistic regression model prediting admission into UCLA using `gre`, `gpa`, and the prestige of the undergraduate schools.  Use the highest prestige undergraduate schools as your reference point.

In [29]:
# TODO
model = smf.logit(formula = 'admit ~ gre + gpa + prestige2 + prestige3 + prestige4', data=dfnew).fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.573854
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  admit   No. Observations:                  397
Model:                          Logit   Df Residuals:                      391
Method:                           MLE   Df Model:                            5
Date:                Thu, 20 Oct 2016   Pseudo R-squ.:                 0.08166
Time:                        18:08:07   Log-Likelihood:                -227.82
converged:                       True   LL-Null:                       -248.08
                                        LLR p-value:                 1.176e-07
==============================================================================
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept     -3.8769      1.142     -3.393      0.001        -6.116    -1.638
gre            0.0022      0.001      2.028      0.043      7.44e-05     0.004
gpa            0.7793      0.333      2.344      0.019         0.128     1.431
prestige2     -0.6801      0.317     -2.146      0.032        -1.301    -0.059
prestige3     -1.3387      0.345     -3.882      0.000        -2.015    -0.663
prestige4     -1.5534      0.417     -3.721      0.000        -2.372    -0.735
==============================================================================
"""

> ### Question 13.  Print the model's summary results.

In [ ]:
# TODO

> ### Question 14.  What are the odds ratios of the different features and their 95% confidence intervals?

In [ ]:
# TODO

> ### Question 15.  Interpret the odds ratio for `prestige = 2`.

Answer:

> ### Question 16.  Interpret the odds ratio of `gpa`.

Answer:

> ### Question 17.  Assuming a student with a GRE of 800 and a GPA of 4.  What is his/her probability of admission  if he/she come from a tier-1, tier-2, tier-3, or tier-4 undergraduate school?

In [32]:
# TODO

model.predict(pd.DataFrame([[800, 4, 0, 0, 0]], columns=dfnew.columns[1:]))

array([ 0.73403998])

In [33]:
model.predict(pd.DataFrame([[800, 4, 1, 0, 0]], columns=dfnew.columns[1:]))

array([ 0.58299512])

Answer:

## Part D. Moving the model from `statsmodels` to `sklearn`

> ### Question 18.  Let's assume we are satisfied with our model.  Remodel it (same features) using `sklearn`.  When creating the logistic regression model with `LogisticRegression(C = 10 ** 2)`.

In [34]:
# TODO

from sklearn.linear_model import LogisticRegression

In [37]:
# create instance of LogisticRegression
logreg = LogisticRegression(C=10**2)
# logreg.fit(inputfeatures, outputfeature)
logreg.fit(dfnew.drop('admit', axis=1, inplace=False), dfnew['admit'])

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
logreg.predict_proba([[800, 4, 0, 0, 0]])

array([[ 0.28814605,  0.71185395]])

> ### Question 19.  What are the odds ratios for the different variables and how do they compare with the odds ratios calculated with `statsmodels`?

In [ ]:
# TODO

Answer:

> ### Question 20.  Again assuming a student with a GRE of 800 and a GPA of 4.  What is his/her probability of admission  if he/she come from a tier-1, tier-2, tier-3, or tier-4 undergraduate school?

In [ ]:
# TODO

Answer: